// Generated by scripts/devnet/sync-abis.sh — do not edit by hand.
// Source: contracts/out/PublicImmunityVote.sol/PublicImmunityVote.json
export const PublicImmunityVoteAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "game_", type: "address", internalType: "contract SurvivalGame" },
      { name: "lifeToken_", type: "address", internalType: "contract RosterToken" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "ballotOf",
    inputs: [
      { name: "", type: "uint256", internalType: "uint256" },
      { name: "", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "game",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract SurvivalGame" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "immuneFor",
    inputs: [{ name: "round", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "lifeToken",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract RosterToken" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pendingRound",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "voteForImmunity",
    inputs: [{ name: "candidate", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "votesFor",
    inputs: [
      { name: "", type: "uint256", internalType: "uint256" },
      { name: "", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "ImmunityVoteCast",
    inputs: [
      { name: "round", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "voter", type: "address", indexed: true, internalType: "address" },
      { name: "candidate", type: "address", indexed: true, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "CandidateNotAlive",
    inputs: [{ name: "candidate", type: "address", internalType: "address" }],
  },
  { type: "error", name: "NotAlive", inputs: [{ name: "account", type: "address", internalType: "address" }] },
  { type: "error", name: "RoundAlreadyOpen", inputs: [{ name: "round", type: "uint256", internalType: "uint256" }] },
] as const;
