#!/usr/bin/env bash
#
# Regenerates the app's ABI files from the Foundry artifacts.
#
# Run after changing any contract the frontend calls, otherwise the app encodes calls against a
# stale interface — which surfaces as an unexplained revert rather than a type error.
#
# Usage: sync-abis.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUT="$ROOT/app/plugins/game/artifacts"

command -v jq >/dev/null 2>&1 || { echo "jq is required" >&2; exit 1; }

forge build --root "$ROOT/contracts" >/dev/null

for pair in "SurvivalGame:SurvivalGameAbi" "RosterToken:RosterTokenAbi" "PublicImmunityVote:PublicImmunityVoteAbi" "GameFactory:GameFactoryAbi"; do
  name="${pair%%:*}"; var="${pair##*:}"
  src="$ROOT/contracts/out/$name.sol/$name.json"
  [ -f "$src" ] || { echo "missing artifact: $src" >&2; exit 1; }

  # `as const` must sit on the SAME line as the closing bracket. On its own line, automatic
  # semicolon insertion terminates the statement after the array and TypeScript fails to parse.
  abi="$(jq -c '.abi' "$src")"
  {
    printf '// Generated by scripts/devnet/sync-abis.sh — do not edit by hand.\n'
    printf '// Source: contracts/out/%s.sol/%s.json\n' "$name" "$name"
    printf 'export const %s = %s as const;\n' "$var" "$abi"
  } > "$OUT/$name.ts"

  printf '  %-22s %s\n' "$name" "$(wc -c < "$OUT/$name.ts" | tr -d ' ') bytes"
done

echo "ABIs written to app/plugins/game/artifacts/"
